### ISSUE TITLE
How do I use this code?

### ISSUE THREAD

**Issue by arnoudbuzing** [maxitg/InflationSimulator#14]
This looks very interesting. Is there a notebook with examples on how to use it?

**Comment by maxitg** [comment]
Thanks for your interest!

Sorry for replying so late, somehow I did not have notifications turned on for this repository.

In case you are still interested, there is documentation included with this code. If you install a paclet from the releases page, you can just open documentation center, and search `InflationSimulator`, which would open a guide page with links to all symbols, and there are some examples for all of them.

Note though this is a prerelease version so some things are not complete (i.e., arguments checking), and bugs are expected.
